name: Run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 

      - name: Test
        run: make test

      - name: Test cleanup
        run: make test-cleanup || echo ''
